
export const stubUser = {
  "login": "rfinni",
  "id": 1593553,
  "node_id": "MDQ6VXNlcjE1OTM1NTM=",
  "avatar_url": "https://avatars3.githubusercontent.com/u/1593553?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/rfinni",
  "html_url": "https://github.com/rfinni",
  "followers_url": "https://api.github.com/users/rfinni/followers",
  "following_url": "https://api.github.com/users/rfinni/following{/other_user}",
  "gists_url": "https://api.github.com/users/rfinni/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/rfinni/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/rfinni/subscriptions",
  "organizations_url": "https://api.github.com/users/rfinni/orgs",
  "repos_url": "https://api.github.com/users/rfinni/repos",
  "events_url": "https://api.github.com/users/rfinni/events{/privacy}",
  "received_events_url": "https://api.github.com/users/rfinni/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Ryan Finni",
  "company": "@neighborhoods ",
  "blog": "",
  "location": "Chicago, IL",
  "email": null,
  "hireable": null,
  "bio": null,
  "public_repos": 4,
  "public_gists": 6,
  "followers": 3,
  "following": 11,
  "created_at": "2012-03-31T16:20:28Z",
  "updated_at": "2019-02-08T23:30:14Z"
}

export const stubSearchResults = [
  {
    "login": "rfinnie",
    "id": 704589,
    "node_id": "MDQ6VXNlcjcwNDU4OQ==",
    "avatar_url": "https://avatars3.githubusercontent.com/u/704589?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/rfinnie",
    "html_url": "https://github.com/rfinnie",
    "followers_url": "https://api.github.com/users/rfinnie/followers",
    "following_url": "https://api.github.com/users/rfinnie/following{/other_user}",
    "gists_url": "https://api.github.com/users/rfinnie/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/rfinnie/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/rfinnie/subscriptions",
    "organizations_url": "https://api.github.com/users/rfinnie/orgs",
    "repos_url": "https://api.github.com/users/rfinnie/repos",
    "events_url": "https://api.github.com/users/rfinnie/events{/privacy}",
    "received_events_url": "https://api.github.com/users/rfinnie/received_events",
    "type": "User",
    "site_admin": false,
    "score": 89.29493
  },
  {
    "login": "rfinni",
    "id": 1593553,
    "node_id": "MDQ6VXNlcjE1OTM1NTM=",
    "avatar_url": "https://avatars3.githubusercontent.com/u/1593553?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/rfinni",
    "html_url": "https://github.com/rfinni",
    "followers_url": "https://api.github.com/users/rfinni/followers",
    "following_url": "https://api.github.com/users/rfinni/following{/other_user}",
    "gists_url": "https://api.github.com/users/rfinni/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/rfinni/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/rfinni/subscriptions",
    "organizations_url": "https://api.github.com/users/rfinni/orgs",
    "repos_url": "https://api.github.com/users/rfinni/repos",
    "events_url": "https://api.github.com/users/rfinni/events{/privacy}",
    "received_events_url": "https://api.github.com/users/rfinni/received_events",
    "type": "User",
    "site_admin": false,
    "score": 52.276836
  },
  {
    "login": "rfinnigan",
    "id": 7691781,
    "node_id": "MDQ6VXNlcjc2OTE3ODE=",
    "avatar_url": "https://avatars1.githubusercontent.com/u/7691781?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/rfinnigan",
    "html_url": "https://github.com/rfinnigan",
    "followers_url": "https://api.github.com/users/rfinnigan/followers",
    "following_url": "https://api.github.com/users/rfinnigan/following{/other_user}",
    "gists_url": "https://api.github.com/users/rfinnigan/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/rfinnigan/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/rfinnigan/subscriptions",
    "organizations_url": "https://api.github.com/users/rfinnigan/orgs",
    "repos_url": "https://api.github.com/users/rfinnigan/repos",
    "events_url": "https://api.github.com/users/rfinnigan/events{/privacy}",
    "received_events_url": "https://api.github.com/users/rfinnigan/received_events",
    "type": "User",
    "site_admin": false,
    "score": 35.838554
  },
  {
    "login": "rfinnigs",
    "id": 6342615,
    "node_id": "MDQ6VXNlcjYzNDI2MTU=",
    "avatar_url": "https://avatars1.githubusercontent.com/u/6342615?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/rfinnigs",
    "html_url": "https://github.com/rfinnigs",
    "followers_url": "https://api.github.com/users/rfinnigs/followers",
    "following_url": "https://api.github.com/users/rfinnigs/following{/other_user}",
    "gists_url": "https://api.github.com/users/rfinnigs/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/rfinnigs/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/rfinnigs/subscriptions",
    "organizations_url": "https://api.github.com/users/rfinnigs/orgs",
    "repos_url": "https://api.github.com/users/rfinnigs/repos",
    "events_url": "https://api.github.com/users/rfinnigs/events{/privacy}",
    "received_events_url": "https://api.github.com/users/rfinnigs/received_events",
    "type": "User",
    "site_admin": false,
    "score": 18.359406
  },
  {
    "login": "rfinnie-canonical",
    "id": 41756600,
    "node_id": "MDQ6VXNlcjQxNzU2NjAw",
    "avatar_url": "https://avatars0.githubusercontent.com/u/41756600?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/rfinnie-canonical",
    "html_url": "https://github.com/rfinnie-canonical",
    "followers_url": "https://api.github.com/users/rfinnie-canonical/followers",
    "following_url": "https://api.github.com/users/rfinnie-canonical/following{/other_user}",
    "gists_url": "https://api.github.com/users/rfinnie-canonical/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/rfinnie-canonical/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/rfinnie-canonical/subscriptions",
    "organizations_url": "https://api.github.com/users/rfinnie-canonical/orgs",
    "repos_url": "https://api.github.com/users/rfinnie-canonical/repos",
    "events_url": "https://api.github.com/users/rfinnie-canonical/events{/privacy}",
    "received_events_url": "https://api.github.com/users/rfinnie-canonical/received_events",
    "type": "User",
    "site_admin": false,
    "score": 17.75509
  }
];
